source 'http://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', "~> 8.0.0"
gem 'cow_proxy', :git => 'https://github.com/mcr/cow_proxy.git'
gem 'zeitwerk'

gem 'psych', '~> 3.3'

# Use postgresql as the database for Active Record
gem 'sqlite3', "~> 1.4.0"
gem 'pg'

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'log4r'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# used by IP address management in ANIMA ACP
gem 'ipaddress', :git => 'https://github.com/mcr/ipaddress.git', :tag => 'v0.9.0mcr'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'

# raven for sentry.io
gem "sentry-ruby"
gem "sentry-rails"

gem 'openssl', :path => '/app/minerva/ruby-openssl'
gem 'sassc', "~> 2.3.0"    # because compiled extension
gem 'sass-rails'

# for github warning
gem 'warden', '~> 1.2.3'
gem "devise", ">= 4.7.1"
gem "rake", ">= 12.3.3"
gem "netaddr", ">= 2.0.4"
gem "actionview", ">= 5.2.7.1"
gem "yard", ">= 0.9.20"
gem "websocket-extensions", ">= 0.1.5"
gem "rack", ">= 2.2.6.4"
gem "loofah", ">= 2.19.1"
gem "actionpack", ">= 5.2.6.2"
gem "activerecord", ">= 5.2.8.1"
gem "json", ">= 2.3.0"
gem "rexml", ">= 3.2.5"
gem "addressable", ">= 2.8.0"
gem "nokogiri", ">= 1.18.9"
gem "rails-html-sanitizer", ">= 1.4.4"
gem "tzinfo", ">= 1.2.10"
gem "globalid", ">= 1.0.1"
gem 'thor', ">= 1.4.0"
gem 'activestorage', ">= 8.0.2.1"

# use this to get full decoding of HTTP Accept: headers, to be able to
# split off smime-type=voucher in pkcs7-mime, and other parameters
gem 'http-accept'

# for LetsEncrypt
gem 'acme-client'
gem 'dns-update', :git => 'https://github.com/CIRALabs/dns-update.git', :branch => 'aaaa_rr'

# for static files
gem 'rails-static-router'

# used to generate multipart bodies
gem 'multipart_body', :git => 'https://github.com/AnimaGUS-minerva/multipart_body.git', :branch => 'binary_http_multipart'
gem 'ecdsa',   :git => 'https://github.com/AnimaGUS-minerva/ruby_ecdsa.git', :branch => 'ecdsa_interface_openssl'
gem 'chariwt', :git => 'https://github.com/AnimaGUS-minerva/ChariWTs.git', :branch => 'v0.11.0'
gem 'jwt'

gem 'thin'
gem 'googleauth'
gem 'google-apis-fcm_v1'
