apiVersion: batch/v1
kind: Job
metadata:
  name: shg-comet-migrations
  namespace: shg
spec:
  template:
    spec:
      containers:
      - image: docker-registry.infra.01.k-ciralabs.ca/ciralabs/shg-highway:comet-0.9.3
        imagePullPolicy: Always
        name: shg-comet
        command: ["bundle", "exec", "rake", "db:migrate"]
        resources: 
          requests:
            memory: 128Mi
            cpu: 100m
      restartPolicy: Never
