apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shg
commonLabels:
  app: shg-comet
images:
- name: docker-registry.infra.01.k-ciralabs.ca/ciralabs/shg-highway
  newTag: comet-0.9.8
resources:
- 00-shg-comet-pvc.yaml
- 06-shg-comet-certs-sealedsecret.yaml
- 07-shg-comet-sealedsecret.yaml
- 16-shg-comet-migrations-job.yaml
- 26-shg-comet-deployment.yaml
- 31-shg-comet-service.yaml
- 36-shg-comet-ingress.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- name: shg-comet-files
  files:
    - config/database.yml
    - config/secrets.yml
    - config/initializers/acme.rb
    - config/environments/production.rb
- name: shg-comet-env
  literals:
    - RAILS_ENV=production
    - MASA_URL=https://shg-comet.shg.01.k-ciralabs.ca/
    - ADMIN_INTERFACE=false
    - GEM_HOME=/usr/local/bundle
    - CERTDIR=/app/certificates