# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c1bd33ec2251b5383359630025b412324bad61b47fac453ce4e259996ba63100f63052522bae9ed7bd22b4bd8db867519005a43868f06ed14025019ab72c058

test:
  secret_key_base: 10c8120ede21e4d8224531502324733bc48685bba09ef654d52d8d258f8c5f3afb53f80ed92e057089cc12f20ac3a1c24340a79ff82b2b0190530b79c26b0e44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 10c8120ede21e4d8224531502324733bc48685bba09ef654d52d8d258f8c5f3afb53f80ed92e057089cc12f20ac3a1c24340a79ff82b2b0190530b79c26b0e44

